# Exported from Render on 2024-07-17T16:32:57Z
services:
- type: web
  name: chat-whatsapp-Cloude
  runtime: python
  repo: https://github.com/Pablojvizz/chat-whatsapp-Cloude
  plan: free
  envVars:
  - key: TWILIO_AUTH_TOKEN
    sync: false
  - key: TWILIO_ACCOUNT_SID
    sync: false
  - key: GOOGLE_API_KEY
    sync: false
  region: oregon
  buildCommand: |
    # Install necessary build tools
    apt-get update && apt-get install -y wget build-essential
    # Download and install SQLite
    wget https://www.sqlite.org/2021/sqlite-autoconf-3350500.tar.gz
    tar xvfz sqlite-autoconf-3350500.tar.gz
    cd sqlite-autoconf-3350500
    ./configure
    make
    make install
    # Update the library path to use the newly installed SQLite version
    export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
    # Install Python dependencies
    pip install -r requirements.txt
  startCommand: python main.py
  autoDeploy: false
  pullRequestPreviewsEnabled: true
version: "1"

